"""empty message

Revision ID: 37f4fdd949b1
Revises: 88396a88dffd
Create Date: 2020-11-03 20:34:09.678351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f4fdd949b1'
down_revision = '88396a88dffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
