"""empty message

Revision ID: 78e87e504fa4
Revises: b90d2155059a
Create Date: 2020-11-05 00:15:11.877532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e87e504fa4'
down_revision = 'b90d2155059a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals_relations', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals_relations', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
