"""empty message

Revision ID: b90d2155059a
Revises: a7e77d58090c
Create Date: 2020-11-04 21:57:27.400522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b90d2155059a'
down_revision = 'a7e77d58090c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals_relations', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals_relations', 'quantity')
    # ### end Alembic commands ###
